### PR TITLE
Add flake8 to find syntax errors & undefined names

### PR DESCRIPTION
**Pull request by cclauss**
The error is fixed in #12

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks! Can you rebase now that I've merged #12?

**Comment by cclauss** [comment]
This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.

**Comment by jakevdp** [comment]
Yes, I know there are no conflicts, but I'd like to see the travis tests pass on this PR before I merge it. Can you rebase your branch? You don't need write access to the main repository to do that. Thanks!

**Comment by cclauss** [comment]
Clean and green.

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
