### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kanitw**
I think what's promising about this library is people can use this library to create a plot that people can easily export to share or further customize (or even blend with other plots).

### CODE REVIEW

**Comment by jakevdp** [comment]
That's a good point... I mention that a bit [in the documentation](https://jakevdp.github.io/pdvega/advanced.html)... we could probably add more about sharing/customization options.

Or even add a section to the README about the vision of Vega/Vega-Lite with regards to sharing visualizations (mention wikimedia, etc.)

**Comment by jakevdp** [comment]
I added some verbiage about this to the README; let me know what you think: https://github.com/jakevdp/pdvega#why-vega-lite

**Comment by domoritz** [comment]
I love it!

**Comment by kanitw** [comment]
<3 it too :)

**Pull request merged**
